# Generated by Django 5.2.3 on 2025-07-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0002_alter_captchastore_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchastore',
            name='challenge',
            field=models.CharField(max_length=256),
        ),
    ]
